[package]
org = "ballerina"
name = "websocket"
version = "2.1.0"
authors = ["Ballerina"]
keywords = ["ws", "network", "bi-directional", "streaming", "service", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-websocket"
icon = "resources/icon.png"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../native/build/libs/websocket-native-2.1.0.jar"

[[platform.java11.dependency]]
path = "./lib/http-native-2.1.0.jar"

[[platform.java11.dependency]]
path = "./lib/mime-native-2.1.0.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/websocket-test-utils-2.1.0.jar"
scope = "testOnly"
