[package]
org = "ballerina"
name = "websocket"
version = "2.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/websocket-native-2.0.0.jar"

[[platform.java11.dependency]]
path = "./lib/http-native-2.0.0-20210903-211100-0e8578b.jar"

[[platform.java11.dependency]]
path = "./lib/mime-native-2.0.0-20210902-230300-b58f48e.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.65.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.65.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.65.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.65.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.65.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.65.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.65.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.65.Final.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/websocket-test-utils-2.0.0.jar"
scope = "testOnly"
