[package]
org = "ballerina"
name = "websocket"
version = "2.9.0"
authors = ["Ballerina"]
keywords = ["ws", "network", "bi-directional", "streaming", "service", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-websocket"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "websocket-native"
version = "2.9.0"
path = "../native/build/libs/websocket-native-2.9.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "http-native"
version = "2.9.0"
path = "./lib/http-native-2.9.0-20230621-065800-bb69fb5.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mime-native"
version = "2.8.0"
path = "./lib/mime-native-2.8.0-20230620-205000-a1e0453.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.3.0"
path = "./lib/constraint-native-1.3.0-20230620-195700-ca941bc.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.86.Final"
path = "./lib/netty-common-4.1.86.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.86.Final"
path = "./lib/netty-buffer-4.1.86.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.86.Final"
path = "./lib/netty-transport-4.1.86.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.86.Final"
path = "./lib/netty-resolver-4.1.86.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.86.Final"
path = "./lib/netty-handler-4.1.86.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "4.1.86.Final"
path = "./lib/netty-codec-http-4.1.86.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.1.86.Final"
path = "./lib/netty-codec-4.1.86.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "4.1.86.Final"
path = "./lib/netty-handler-proxy-4.1.86.Final.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/websocket-test-utils-2.9.0-SNAPSHOT.jar"
scope = "testOnly"
