[package]
org = "ballerina"
name = "websocket"
version = "2.5.1"
authors = ["Ballerina"]
keywords = ["ws", "network", "bi-directional", "streaming", "service", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-websocket"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.3.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "websocket-native"
version = "2.5.1"
path = "../native/build/libs/websocket-native-2.5.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "http-native"
version = "2.5.0"
path = "./lib/http-native-2.5.0.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mime-native"
version = "2.5.0"
path = "./lib/mime-native-2.5.0.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.0.1"
path = "./lib/constraint-native-1.0.1.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/websocket-test-utils-2.5.1-SNAPSHOT.jar"
scope = "testOnly"
