[plugin]
id = "websocket-compiler-plugin"
class = "io.ballerina.stdlib.websocket.plugin.WebSocketCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/websocket-compiler-plugin-2.11.2-SNAPSHOT.jar"
